name: minimal_example
description: Example app for minimal package
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dart_mappable: ^4.5.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  minimal_mvn:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/minimal.svg
    # Needed to read package version at runtime
    - ../pubspec.yaml

  # Enable generation of localized Strings from arb files.
  generate: true
